### ISSUE TITLE
Roadmap 

### ISSUE THREAD

**Issue by williamespindola** [williamespindola/shark-bowl#1]
- [ ] RESTFull API following [Act Three: The Maturity Heuristic](https://www.crummy.com/writing/speaking/2008-QCon/act3.html);
- [ ] JWT Authentication
- [ ] Mobile app
- [ ] User register via social link
- [ ] Some one create a event and manage it
- [ ] User submit a subject to some event
- [ ] Manager submit subjects 
- [ ] Manager manage event starting/continuing/stoping/finishing some subject
- [ ] Calculate the time needed for each subject
- [ ] Share event
- [ ] User comment some subject, maybe use some chatter for this
